/* ============================================================
   GENERATED by scripts/optimise-project-images.mjs — do not hand-edit.

   Old image URL -> new image URL, served as a permanent 301 by
   src/middleware.ts. Kept indefinitely, on purpose: a 301 passes
   ranking signals, and these URLs are already live in links people
   have shared and in the Open Graph cards WhatsApp and Facebook have
   cached. See IMAGE-SEO-BRIEF.md §3.2.

   34 entries.
   ============================================================ */
export const imageRedirects: Record<string, string> = {
  "/images/Project_Images/Dhruva/Aerial_View/DSC_0012.jpeg": "/images/projects/dhruva/photos/dhruva-aerial-view-01.webp",
  "/images/Project_Images/Dhruva/Aerial_View/DSC_0015.jpeg": "/images/projects/dhruva/photos/dhruva-aerial-view-02.webp",
  "/images/Project_Images/Dhruva/Aerial_View/DSC_0017.jpeg": "/images/projects/dhruva/photos/dhruva-aerial-view-03.webp",
  "/images/Project_Images/Dhruva/Aerial_View/DSC_0025.jpeg": "/images/projects/dhruva/photos/dhruva-aerial-view-04.webp",
  "/images/Project_Images/Dhruva/Aerial_View/DSC_0036.jpeg": "/images/projects/dhruva/photos/dhruva-aerial-view-05.webp",
  "/images/Project_Images/Dhruva/Aerial_View/DSC_0045.jpeg": "/images/projects/dhruva/photos/dhruva-aerial-view-06.webp",
  "/images/Project_Images/Dhruva/Aerial_View/IMG20260627113437.jpeg": "/images/projects/dhruva/photos/dhruva-aerial-view-07.webp",
  "/images/Project_Images/Dhruva/Aerial_View/IMG20260627113444.jpeg": "/images/projects/dhruva/photos/dhruva-aerial-view-08.webp",
  "/images/Project_Images/Dhruva/Aerial_View/IMG20260627115053.jpeg": "/images/projects/dhruva/photos/dhruva-aerial-view-09.webp",
  "/images/Project_Images/Dhruva/Corridor/corridor.png": "/images/projects/dhruva/photos/dhruva-corridor-01.webp",
  "/images/Project_Images/Dhruva/Corridor/DSC_0049.jpeg": "/images/projects/dhruva/photos/dhruva-corridor-02.webp",
  "/images/Project_Images/Dhruva/Corridor/IMG20260627113731.jpeg": "/images/projects/dhruva/photos/dhruva-corridor-03.webp",
  "/images/Project_Images/Dhruva/Exterior/DSC_0005.jpeg": "/images/projects/dhruva/photos/dhruva-exterior-01.webp",
  "/images/Project_Images/Dhruva/Exterior/DSC_0006.jpeg": "/images/projects/dhruva/photos/dhruva-exterior-02.webp",
  "/images/Project_Images/Dhruva/Exterior/IMG20260627112705.jpeg": "/images/projects/dhruva/photos/dhruva-exterior-03.webp",
  "/images/Project_Images/Dhruva/Lift/DSC_0205.jpeg": "/images/projects/dhruva/photos/dhruva-lift-01.webp",
  "/images/Project_Images/Dhruva/Lift/IMG20260627140541.jpeg": "/images/projects/dhruva/photos/dhruva-lift-02.webp",
  "/images/Project_Images/Dhruva/Lobby/DSC_0199.jpeg": "/images/projects/dhruva/photos/dhruva-lobby-01.webp",
  "/images/Project_Images/Dhruva/Lobby/IMG20260627140435.jpeg": "/images/projects/dhruva/photos/dhruva-lobby-02.webp",
  "/images/Project_Images/Dhruva/Lobby/IMG20260627140500.jpeg": "/images/projects/dhruva/photos/dhruva-lobby-03.webp",
  "/images/Project_Images/Dhruva/Render/dhruva-startrail-scene.png": "/images/projects/dhruva/photos/dhruva-render-01.webp",
  "/images/Project_Images/Shikhar/Aerial_View/DSC_0153.jpeg": "/images/projects/shikhar/photos/shikhar-aerial-view-01.webp",
  "/images/Project_Images/Shikhar/Aerial_View/DSC_0161.jpeg": "/images/projects/shikhar/photos/shikhar-aerial-view-02.webp",
  "/images/Project_Images/Shikhar/Aerial_View/DSC_0166.jpeg": "/images/projects/shikhar/photos/shikhar-aerial-view-03.webp",
  "/images/Project_Images/Shikhar/Aerial_View/DSC_0183.jpeg": "/images/projects/shikhar/photos/shikhar-aerial-view-04.webp",
  "/images/Project_Images/Shikhar/Aerial_View/IMG20260627132223.jpeg": "/images/projects/shikhar/photos/shikhar-aerial-view-05.webp",
  "/images/Project_Images/Shikhar/Aerial_View/IMG20260627132240.jpeg": "/images/projects/shikhar/photos/shikhar-aerial-view-06.webp",
  "/images/Project_Images/Shikhar/Aerial_View/IMG20260627132537.jpeg": "/images/projects/shikhar/photos/shikhar-aerial-view-07.webp",
  "/images/Project_Images/Shikhar/Aerial_View/IMG20260627133708.jpeg": "/images/projects/shikhar/photos/shikhar-aerial-view-08.webp",
  "/images/Project_Images/Shikhar/Exterior/DSC_0108.jpeg": "/images/projects/shikhar/photos/shikhar-exterior-01.webp",
  "/images/Project_Images/Shikhar/Exterior/DSC_0113.jpeg": "/images/projects/shikhar/photos/shikhar-exterior-02.webp",
  "/images/Project_Images/Shikhar/Exterior/DSC_0114.jpeg": "/images/projects/shikhar/photos/shikhar-exterior-03.webp",
  "/images/Project_Images/Shikhar/Exterior/IMG20260627130037.jpeg": "/images/projects/shikhar/photos/shikhar-exterior-04.webp",
  "/images/Project_Images/Shikhar/Interior/IMG20260627131512.jpeg": "/images/projects/shikhar/photos/shikhar-interior-01.webp",
};
