/* ============================================================
   GET /robots.txt
   ------------------------------------------------------------
   Generated, not a static file in public/. The only line in it
   that MUST be right is `Sitemap:`, and that line has to be an
   ABSOLUTE URL at the origin the build was actually made for — a
   sitemap announced at https://nestingtree.in from a build served
   on a bare IP points crawlers at a host that does not answer.

   `astro.config.mjs` already lets PUBLIC_SITE_URL move the origin
   at build time (it is the documented path for serving from an EC2
   public IP before DNS exists), and canonical + og:image are both
   derived from `Astro.site` for exactly this reason. Hard-coding
   the origin here would be the one absolute URL on the site that
   does not follow it.

   Prerendered, so this lands in the build output as a plain file at
   dist/client/robots.txt and nginx serves it from disk.

   THREE THINGS THIS FILE IS NOT.

   It is not a security control. Everything named below is public
   either way; a Disallow line is a request that well-behaved bots
   honour and a map for the ones that do not. Which is why /studio/
   — the editor sign-in, whose whole defence is that its URL is a
   secret — is deliberately ABSENT here. Naming it, even as a
   prefix, would advertise that the prefix exists. It is kept out of
   the index by `X-Robots-Tag: noindex, nofollow` on the response
   and `noindex` in its markup, which is the right tool: robots.txt
   cannot deindex anything, it only stops a fetch.

   It is not a way to remove a page from search. Disallow stops the
   crawl; a URL that is disallowed but linked to can still be listed
   without a snippet. `noindex` on the page is what removes it, and
   `noindex` only works if the crawler is ALLOWED to fetch the page
   and read it. /thank-you carries both, on purpose, because it has
   nowhere to be linked from.

   And it is not per-page. There is one file for the whole origin,
   matched by longest path prefix, and a named `User-agent:` group
   REPLACES the `*` group for that agent rather than adding to it —
   which is why every blocked crawler below gets a complete group of
   its own rather than an extra line.
   ============================================================ */
import type { APIRoute } from "astro";

export const prerender = true;

/* Backlink and SEO-audit crawlers. These exist to resell a map of the
   web to marketers: they crawl hard, they send no visitors, and this
   site is one small instance serving a few hundred megabytes of
   photography. Blocking them is a bandwidth decision, not an SEO one —
   none of them feed a search engine anyone uses.

   Note what is NOT here: GPTBot, ClaudeBot, PerplexityBot,
   Google-Extended and the other assistant crawlers, which are allowed
   by the `*` group below. Deliberate, decided 22 Aug 2026 — being
   quotable when someone asks an assistant about builders in Navi
   Mumbai is worth more to a company this size than withholding twelve
   pages of public marketing copy. To reverse it, add names to this
   list; do not touch `Allow: /`. */
const BLOCKED_AGENTS = [
  "AhrefsBot",
  "SemrushBot",
  "MJ12bot",
  "DotBot",
  "BLEXBot",
  "dataforseo-bot",
];

export const GET: APIRoute = ({ site }) => {
  const sitemap = new URL("/sitemap-index.xml", site).href;

  const body = [
    "# nestingtree.in — Nesting Tree, residential developer, Navi Mumbai.",
    "# Generated by src/pages/robots.txt.ts. Edit there, not here: this file",
    "# is rebuilt on every deploy and any hand edit is lost.",
    "",
    "User-agent: *",
    "Allow: /",
    "",
    "# The enquiry-form confirmation page. It reads ?project / ?status, so",
    "# every visit to it is a different URL of no use to anyone arriving",
    "# cold. It also carries `noindex, follow` in its own markup — see",
    "# src/pages/thank-you.astro. Both, on purpose: this line stops the",
    "# crawl, the meta tag is what keeps it out of the index if it is ever",
    "# reached by a link.",
    "Disallow: /thank-you",
    "",
    "# Endpoints, not pages. /api/contact takes the enquiry form and",
    "# /api/content the in-page editor; a GET on either is a 405 that costs",
    "# a crawl slot and returns nothing readable.",
    "Disallow: /api/",
    "",
    "# Background films — several MB each, decorative, and already",
    "# represented to a crawler by their poster images. Blocking them keeps",
    "# a small server's bandwidth for pages. If Search Console ever reports",
    "# them as blocked page resources, this is the line to remove.",
    "Disallow: /*.mp4$",
    "",
    "# Nothing on this site is meant to be a downloadable document. If one",
    "# is ever dropped into public/ by accident it stays out of search",
    "# results instead of becoming one.",
    "Disallow: /*.doc$",
    "Disallow: /*.docx$",
    "Disallow: /*.xls$",
    "Disallow: /*.xlsx$",
    "Disallow: /*.pdf$",
    "",
    ...BLOCKED_AGENTS.flatMap((agent) => [`User-agent: ${agent}`, "Disallow: /", ""]),
    "# Absolute, and pointed at the origin this build was made for.",
    `Sitemap: ${sitemap}`,
    "",
  ].join("\n");

  return new Response(body, {
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
};
